export const FETCH_VOLUNTEERS = 'FETCH_VOLUNTEERS';
export const ADD_VOLUNTEER = 'ADD_VOLUNTEER';
export const DELETE_VOLUNTEER = 'DELETE_VOLUNTEER';

export const FETCH_CALLS = 'FETCH_CALLS';
export const FETCH_CALLS_BY_DATE = 'FETCH_CALLS_BY_DATE';
export const ADD_CALL = 'ADD_CALL';

export const FETCH_FORM = 'FETCH_FORM';
export const SET_ADMIN = 'SET_ADMIN';
