export default {
    1: 'Gubitak',
    2: 'Usamljenost',
    3: 'Partnerski',
    4: 'Porodični (sa roditeljima ili članovima porodice)',
    5: 'Problem na radnom mestu, školi ili fakultetu',
    6: 'Egzistencijalni problemi (nezaposlenost, siromaštvo, nemanje perspektive, opšte nezadovoljstvo životom,...)',
    7: 'Bolest zavisnosti: Alkoholizam',
    8: 'Bolest zavisnosti: Narkomanija',
    9: 'Mentalni (psihički) poremećaj',
    10: 'Problem seksualne prirode (sex. disfunkcija, masturbacija, frigidnost, nimfomanija, promiskuitet, veličina polnog organa, fetišizam, incest, voajerizam, strah od odnosa,...)',
    11: 'Problem usled sex. Orijentacije (homoseksualnost, biseksualnost, transseksualnost, transvestiti)',
    12: 'Telesna bolest',
    13: 'Invaliditet',
    14: 'Zlostavljanje (svi vidovi zlostavljanja)',
    15: 'Poziv za treću osobu',
    16: 'Manipulativni',
    17: 'DRUGO (obavezno dopisati u napomeni i u vel registru koja vrsta problema!)',
};
